---
wildfly_systemd:
  user: "{{ wildfly_user }}"
  group: "{{ wildfly_group }}"
  home: "{{ wildfly_home }}"
  config: "{{ wildfly_config_custom_file | basename if wildfly_config_custom_file | length > 0 else wildfly_config_base }}"
  config_custom: "{{ wildfly_config_custom_file }}"
  enabled: "{{ wildfly_systemd_unit_enabled }}"
  yml_config:
    base_path: '/modules/system/layers/base'
    eap_path: 'modules/system/layers/base/.overlays/layer-base-jboss-eap-'
    path: /org/jboss/as/controller/main/dir/META-INF/services
    file: org.jboss.as.controller.persistence.ConfigurationExtension
  jvm_version_command:
    RedHat: "rpm -ql {{ wildfly_java_package_name }} | grep -Po '/usr/lib/jvm/.*(?=/bin/java$)'"
    Debian: "update-alternatives --query java | grep 'Value: ' | grep -o '/.*/jre'"
  selinux:
    pid_path: "{{ wildfly_pidfile_homedir }}"
