---
- name: "Ensure required params for JBoss CLI have been provided"
  ansible.builtin.assert:
    that:
      - jboss_home is defined
      - jboss_cli_query is defined or jboss_cli_file is defined
      - jboss_cli_controller_host is defined
      - jboss_cli_controller_port is defined
    fail_msg: "Missing required parameters to execute JBoss CLI."
    quiet: true

- name: "Ensure server's management interface is reachable"
  ansible.builtin.wait_for:
    host: "{{ jboss_cli_controller_host }}"
    port: "{{ jboss_cli_controller_port }}"
    timeout: 10
    delay: 1
    sleep: 2

- name: "Execute CLI query {{ jboss_cli_query | default(jboss_cli_file) }}"
  ansible.builtin.command: >
    {{ jboss_cli_path_to_script | default(jboss_home + '/bin/jboss-cli.sh') }} -c
    {{ '--command=' + jboss_cli_query if jboss_cli_query is defined else '' }}
    {{ '--file=' + jboss_cli_file if jboss_cli_file is defined else '' }}
    --controller={{ jboss_cli_controller_host }}:{{ jboss_cli_controller_port }}
    --timeout={{ jboss_cli_timeout * 1000 if jboss_cli_timeout is defined else 5000 }}
    {{ '' if jboss_cli_output_dmr is defined else '--output-json' }}
  register: cli_result
  changed_when: false
  become: yes
